import "./globals.css";
import { Providers } from "@src/app/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen m-0 p-0 box-border dark bg-gray-700">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
